name: CI - Push to master deploys to staging

on:
  push:
    branches: [ master ]

jobs:
  build:

    name: Deploy master to staging on push to master
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Install the CF CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli

      - name: Authenticate with CloudFoundry
        env:
          CF_USERNAME: ${{ secrets.DEPLOY_STAGING_USERNAME }}
          CF_PASSWORD: ${{ secrets.DEPLOY_STAGING_PASSWORD }}
          CF_ORG: global-digital-marketplace
          CF_SPACE: dbg-staging
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth
          cf target -o ${CF_ORG} -s ${CF_SPACE}

      - name: Tag deployment
        run: |
          echo $(git log --format="%H" -n 1) > commit_ref

      - name: Deploy to staging
        env:
          CF_MANIFEST: staging
        run: |
          cf push -f manifest-${CF_MANIFEST}.yml --strategy rolling
